package body body Neo.File.Image is
  --package body FITS  is separate;
  --package body TGA   is separate;
  --package body PCX   is separate;
  --package body GIF   is separate;
  --package body TIFF  is separate;
  --package body PPM   is separate;
  --package body XPM   is separate;
  --package body BMP   is separate;
  --package body JPEG  is separate;
  --package body PNG   is separate;
  --package body DXT   is separate;
  --package body JPGE2 is separate;
  --package body VTF   is separate;
  --package body PVRTC is separate;
  --package body ETC1  is separate;
  --package body ETC2  is separate;
  --package body ATC   is separate;
  --package body ASTC  is separate;
  procedure Save (Name : in String_2; Item : in Record_Graphic) renames Graphic.Save;
  function Load  (Name : in String_2) return Record_Graphic     renames Graphic.Load;
end Neo.File.Image;
